DancingGoat/Models/ViewModels/MoreButtonPartialViewModel.cs
namespace DancingGoat.Models
{
    public class MoreButtonPartialViewModel
    {
        public string Text { get; set; }
        public string Action { get; set; }
        public string Controller { get; set; }
    }
}

DancingGoat/ViewComponents/CompanyAddressViewComponent.cs
using DancingGoat.Models;
using Kentico.Kontent.Delivery.Abstractions;
using Kentico.Kontent.Delivery.Urls.QueryParameters;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace DancingGoat.ViewComponents
{
    public class CompanyAddressViewComponent : ViewComponent
    {
        public IDeliveryClient DeliveryClient { get; }

        public CompanyAddressViewComponent(IDeliveryClientFactory deliveryClientFactory)
        {
            DeliveryClient = deliveryClientFactory.Get();
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var contact = await DeliveryClient.GetItemAsync<Home>("home", new ElementsParameter(Home.ContactCodename));
            return View(contact.Item.Contact);
        }
    }
}

DancingGoat/ViewComponents/LanguageSelectorViewComponent.cs
using Kentico.Kontent.Delivery.Abstractions;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace DancingGoat.ViewComponents
{
    public class LanguageSelectorViewComponent : ViewComponent
    {
        public IDeliveryClient DeliveryClient { get; }

        public LanguageSelectorViewComponent(IDeliveryClient deliveryClient)
        {
            DeliveryClient = deliveryClient;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var langs = await DeliveryClient.GetLanguagesAsync();            
            return View(langs.Languages);
        }
    }
}

DancingGoat/Views/Shared/HeadersMetadata.cshtml
@model DancingGoat.Models.IMetadata
@using Microsoft.AspNetCore.Http.Extensions;
<meta name=”description” content="@Model.MetadataMetaDescription" />

<meta property="og:title" content="@Model.MetadataOgTitle" />
<meta property="og:type" content="website" />
<meta property="og:url" content="@(UriHelper.BuildAbsolute(Context.Request.Scheme,
                                                             Context.Request.Host,
                                                             Context.Request.PathBase,
                                                             Context.Request.Path,
                                                             Context.Request.QueryString))" />
<meta property="og:image" content="@(Model.MetadataOgImage?.FirstOrDefault()?.Url)" />
<meta property="og:description" content="@Model.MetadataOgDescription" />

<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@Model.MetadataTwitterSite">
<meta name="twitter:creator" content="@Model.MetadataTwitterCreator">
<meta name="twitter:title" content="@Model.MetadataTwitterTitle">
<meta name="twitter:description" content="@Model.MetadataOgDescription">
<meta name="twitter:image" content="@(Model.MetadataTwitterImage?.FirstOrDefault()?.Url)">

DancingGoat/Views/Shared/ProductListing.cshtml
@model IEnumerable<DancingGoat.Models.IProduct>

@if (Model.Any())
{
    foreach (var product in Model)
    {
        <!-- 3 products on row for large screen -->
        <div class="col-md-6 col-lg-4">
            @Html.DisplayFor(m => product, "Product")
        </div>
    }
}
else
{
    <span class="ContentLabel">@Localizer["Brewers.NoMatchingProducts"]</span>
}

DancingGoat/Views/Shared/_Layout.cshtml
@using DancingGoat.Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - Dancing Goat</title>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="page-wrap">
        <header class="header" role="banner">
            <div class="menu">
                <div class="container">
                    <nav role="navigation">
                        <ul>
                            <li>
                                <a asp-controller="Home" asp-action="Index">@Localizer["Home"]</a>
                            </li>
                            <li>
                                <a asp-controller="Coffees" asp-action="Index">@Localizer["Store"]</a>
                            </li>
                            <li>
                                <a asp-controller="Articles" asp-action="Index">@Localizer["Articles"]</a>
                            </li>
                            <li>
                                <a asp-controller="About" asp-action="Index">@Localizer["AboutUs"]</a>
                            </li>
                            <li>
                                <a asp-controller="Cafes" asp-action="Index">@Localizer["Cafes"]</a>
                            </li>
                            <li>
                                <a asp-controller="Contacts" asp-action="Index">@Localizer["Contact"]</a>
                            </li>
                            <li>
                                <a asp-controller="Partnership" asp-action="Index">@Localizer["Partnership"]</a>
                            </li>
                        </ul>
                    </nav>
                    <div class="additional-menu-buttons user-menu">
                        @await Component.InvokeAsync("LanguageSelector")
                    </div>
                </div>
            </div>
            <div id="message-box" class="container message">
                <partial name="~/Areas/Admin/Views/Shared/_MessagesPartial.cshtml" />
            </div>
            <div class="header-row">
                <div class="container">
                    <div class="col-xs-8 col-md-8 col-lg-4 logo">
                        <h1 class="logo">
                            <a asp-controller="Home" asp-action="Index" class="logo-link">Dancing Goat</a>
                        </h1>
                    </div>
                </div>
            </div>
        </header>
        <div class="container">
            @RenderBody()
        </div>
    </div>
    <div class="footer-wrapper">
        <footer role="contentinfo">
            <div class="footer-container">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4 col-lg-4 footer-col">
                            <p>
                                @await Component.InvokeAsync("CompanyAddress")
                            </p>
                        </div>
                        <div class="col-md-4 col-lg-4 footer-col">
                            <h3>@Localizer["FollowUs.Title"]</h3>
                            <a class="followus-link" href="https://www.facebook.com/Dancing.Goat" target="_blank">
                                <img alt="@Localizer["FollowUsOnFacebook"]" class="" src="~/images/facebook-icon.png" title="@Localizer["FollowUsOnFacebook"]">
                            </a>
                            <a class="followus-link" href="https://twitter.com/DancingGoat78" target="_blank">
                                <img alt="@Localizer["FollowUsOnTwitter"]" class="" src="~/images/twitter-icon.png" title="@Localizer["FollowUsOnTwitter"]">
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container copyright">
                Copyright &copy; @DateTime.Now.Year Dancing Goat. All rights reserved.
            </div>
        </footer>
    </div>
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

DancingGoat/Views/Shared/_MoreButtonPartial.cshtml
@{
    @model DancingGoat.Models.MoreButtonPartialViewModel
}
<div class="row">
    <div class="clear center-text">
        <a asp-controller="@Model.Controller" asp-action="@Model.Action" class="btn btn-more">
            @Model.Text
        </a>
    </div>
</div>

DancingGoat/Views/Shared/_ProductLayout.cshtml
@using Kentico.Kontent.Delivery.Abstractions
@model DancingGoat.Models.IProduct
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = Model.ProductProductName;
}
<section title="headers" id="head">
    @await Html.PartialAsync("HeadersMetadata", Model)
</section>
<article class="product-detail">
    <div class="row">
        <div class="col-md-12">
            <header>
                <h2>@Html.DisplayFor(vm => vm.ProductProductName)</h2>
            </header>
        </div>
    </div>
    <div class="row-fluid">
        <div class="col-lg-7 col-md-6">
            <figure class="image">
                <img-asset asset="@Model.ProductImage.First()" />
            </figure>
            <div class="description">
                @Html.Raw(string.Join("\n", Model.ProductShortDescription ?? (Model.ProductLongDescription ?? Enumerable.Empty<IRichTextBlock>())))
                @RenderSection("ProductSpecificProperties", false)
            </div>
        </div>
        @RenderSection("ProductSpecificForm", false)
    </div>
</article>

@section Scripts
{
    @RenderSection("Scripts", false)
}

DancingGoat/Views/Shared/_StoreLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container product-page-container">
    <nav role="navigation" class="sub-menu row">
        <div class="store-menu-list row">
            <ul>
                <li>
                    <a asp-controller="Coffees" asp-action="Index">@Localizer["Coffees"]</a>
                </li>
                <li>
                    <a asp-controller="Brewers" asp-action="Index">@Localizer["Brewers"]</a>
                </li>
            </ul>
        </div>
    </nav>
    @RenderBody()
</div>

@section Scripts {
    @RenderSection("scripts", required: false)
}